name: unit-test-run
on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  job-1:
      runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v4
          with:
            node-version: '24'
        - name: install
          run: npm install
        - name: jest
          run: npm test
        - name: generate report
          run: npm run ci:test
          
  job-2:
     runs-on: ubuntu-latest
     needs: 
       - job-1
     steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2.1.2
        id: coverage
        with:
          annotations: true
          package-manager: npm
          test-script: npm ci:test
          icons: emoji
      
